package procedures.ghidra.program.model.data;

import java.io.IOException;
import java.io.StringWriter;

import com.google.gson.JsonObject;

import ghidra.program.model.data.DataType;
import ghidra.program.model.data.DataTypeWriter;

import procedures.RpcContext;
import procedures.RpcProcedure;
import procedures.RpcResponse;

/**
 * Procedure ShowDataType: read a single data type by full path
 * ({@code /Category/Sub/Name}) and return its full description (struct fields,
 * enum entries, typedef base, etc.) plus a C declaration. Read-only.
 *
 * <p>Response shape:
 * <ul>
 *   <li>{@code kind}, {@code name}, {@code path}, {@code category}, {@code size},
 *       {@code source}, {@code sourceArchive}: scalar fields mirroring the
 *       top-level keys of the JSON {@code detail} object, so scripts that
 *       need a single-line summary (e.g. {@code datatype show --path /X |
 *       head -1}) can grep it without parsing the JSON.</li>
 *   <li>{@code detail}: the full JSON object produced by
 *       {@link DataTypeSerializer#describe(DataType)} — same shape as the
 *       pre-C output.</li>
 *   <li>{@code c}: a C-syntax declaration of the type, generated by Ghidra's
 *       {@link DataTypeWriter} (the same engine the GUI's "Export C" uses).
 *       The CLI prints this by default; pass {@code --json} on the CLI side
 *       to see the structured {@code detail} instead. The field is
 *       always present (may be empty for kinds {@code DataTypeWriter} cannot
 *       format, e.g. a malformed composite); the CLI handles the empty case.</li>
 * </ul>
 *
 * <p>Note: {@link ShowResponse} is also used by {@code CreateDataType},
 * {@code ReplaceDataType}, and {@code EditDataType} to confirm what was
 * just written. Those callers now print C code by default too, which is the
 * right behavior ("I just created a struct, show me what it looks like").
 */
public final class ShowDataTypeHandler implements RpcProcedure {

    @Override
    public RpcResponse execute(JsonObject req, RpcContext ctx) throws Exception {
        DataType dt = DataTypeOps.requireDataTypeByPath(ctx, RpcContext.reqStr(req, "path"));
        return new ShowResponse(ctx.program().getDataTypeManager(), dt);
    }

    @Override public boolean mutates() { return false; }

    static final class ShowResponse extends RpcResponse {
        final String kind;
        final String name;
        final String path;
        final String category;
        final long size;
        final String source;
        final String sourceArchive;
        final JsonObject detail;
        final String c;

        /**
         * Build a response for the given data type. Computes both the
         * structured JSON (via {@link DataTypeSerializer#describe}) and the
         * C declaration (via {@link DataTypeWriter#write(DataType[],
         * ghidra.util.task.TaskMonitor)}).
         *
         * <p>The C-declaration write is best-effort: any {@link IOException}
         * from the writer leaves {@code c} as an empty string rather than
         * failing the whole response, because the JSON {@code detail} is the
         * canonical machine-readable form. (In practice {@code DataTypeWriter}
         * on a {@code StringWriter} does not throw — but the safer default is
         * "JSON always, C if we can".)
         */
        ShowResponse(ghidra.program.model.data.DataTypeManager dtm, DataType dt) {
            this.success = true;
            JsonObject o = new DataTypeSerializer(dtm).describe(dt);
            this.kind = o.has("kind") ? o.get("kind").getAsString() : null;
            this.name = o.has("name") ? o.get("name").getAsString() : null;
            this.path = o.has("path") ? o.get("path").getAsString() : null;
            this.category = o.has("category") ? o.get("category").getAsString() : null;
            this.size = o.has("size") ? o.get("size").getAsLong() : 0;
            this.source = o.has("source") ? o.get("source").getAsString() : null;
            this.sourceArchive = o.has("sourceArchive") && !o.get("sourceArchive").isJsonNull()
                ? o.get("sourceArchive").getAsString() : null;
            this.detail = o;
            this.c = writeC(dtm, dt);
        }

        private static String writeC(ghidra.program.model.data.DataTypeManager dtm, DataType dt) {
            // DataTypeWriter.write(DataType[], ...) is the only public write
            // overload that accepts a single DataType — the package-private
            // write(DataType, ...) lives in ghidra.program.model.data and our
            // handler is in procedures.ghidra.program.model.data, so we cannot
            // call it. A 1-element array is the documented equivalent.
            StringWriter sw = new StringWriter();
            try {
                DataTypeWriter w = new DataTypeWriter(dtm, sw);
                w.write(new DataType[] { dt }, ghidra.util.task.TaskMonitor.DUMMY);
            } catch (IOException | ghidra.util.exception.CancelledException e) {
                // Empty string signals "no C available"; the CLI surfaces this
                // as an error and exits non-zero (the user can retry with
                // --json to see the structured detail). We do NOT silently
                // fall back to JSON — that would re-route output without
                // the user knowing it.
                return "";
            }
            // DataTypeWriter ends with a newline; trim so the CLI can print
            // the C declaration cleanly without a trailing blank line.
            String s = sw.toString();
            return s.endsWith("\n") ? s.substring(0, s.length() - 1) : s;
        }
    }
}
