package procedures.ghidra.app.cmd.function;

import com.google.gson.JsonObject;

import procedures.RpcProcedure;
import procedures.RpcContext;
import procedures.RpcResponse;

import ghidra.app.cmd.function.SetVariableDataTypeCmd;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.Parameter;

/**
 * Procedure SetVariableDataTypeCmd: set a variable's data type in a function.
 *
 * <p>{@code --name this} special case: the implicit {@code this} of a
 * {@code __thiscall} member function is auto-generated by Ghidra when the
 * function is associated with a class (via {@code function
 * set-class-association}); its storage is locked and it is retyped at
 * decompile time from the class's DTM struct, NOT by
 * {@code SetVariableDataTypeCmd}. When the user targets it and it isn't
 * found, emit a class-association-aware hint instead of Ghidra's bare
 * "Variable not found" — otherwise the user has no idea they have to
 * reach for a different command.
 */
public final class SetVariableDataTypeCmdHandler implements RpcProcedure {
    @Override
    public RpcResponse execute(JsonObject req, RpcContext ctx) throws Exception {
        Address funcEntry = ctx.requireAddress(RpcContext.reqStr(req, "address"));
        String varName = RpcContext.reqStr(req, "name");
        Function function = ctx.requireFunctionAt(funcEntry);

        RpcResponse result = ctx.applyCommand(new SetVariableDataTypeCmd(funcEntry, varName,
            ctx.requireDataType(RpcContext.reqStr(req, "dataType")),
            ctx.sourceType(RpcContext.optStr(req, "source"))));

        // If the command failed AND the user was targeting the auto-generated
        // implicit `this` of a `__thiscall` member function, Ghidra's bare
        // "Variable not found" / failure-to-retype is uninformative. Two
        // sub-cases:
        //   (a) `this` doesn't exist on the function (no class associated
        //       yet) → point the user at create-class + set-class-association.
        //   (b) `this` exists but is storage-locked (the function IS class-
        //       associated with a `__thiscall` convention) → Ghidra refuses
        //       to retype it; the type is derived from the class's DTM
        //       struct at decompile time.
        if (!result.success && "this".equals(varName)) {
            return RpcResponse.error(thisHint(function, findThisParameter(function) != null));
        }
        return result;
    }

    /**
     * Build the class-association-aware hint for an attempt to retype the
     * implicit {@code this}. {@code thisExists} is true when Ghidra
     * already has an auto-generated {@code this} parameter (i.e. the
     * function is class-associated and the calling convention carries
     * {@code this}).
     */
    private static String thisHint(Function function, boolean thisExists) {
        StringBuilder msg = new StringBuilder();
        if (thisExists) {
            msg.append("Could not retype the implicit `this` of function ")
                .append(function.getName())
                .append(" — its storage is locked (ECX/RCX) and ")
                .append("`function variable set-type` cannot change it. ")
                .append("The decompiler retypes `this` to a pointer to the ")
                .append("function's associated class's DTM struct at decompile ")
                .append("time. To change what `this` points at, edit the DTM ")
                .append("struct of the class (`datatype show --path /<ClassName>`) ")
                .append("or re-associate the function with a different class via ")
                .append("`function set-class-association`. `function decompile` ")
                .append("will then show the new `this` type.");
        } else {
            msg.append("No variable named 'this' in function ")
                .append(function.getName())
                .append(" (the implicit `this` parameter is auto-generated by ")
                .append("`function set-class-association` and only exists after the ")
                .append("function is associated with a class). For a `__thiscall` ")
                .append("member function: (1) `namespace create-class --parent / --name ")
                .append("<ClassName>` to create the class namespace (the decompiler ")
                .append("uses its DTM struct as the `this` type), then (2) ")
                .append("`function set-class-association --class /<ClassName>`. ")
                .append("After association, `this` will appear in `function decompile` ")
                .append("as a pointer to that struct — it is NOT retypeable via ")
                .append("`function variable set-type`.");
        }
        return msg.toString();
    }

    /**
     * Look for a parameter named {@code "this"} (case-sensitive, matching
     * how Ghidra names the auto-generated implicit parameter). Returns
     * null if absent — that's the signal that the function isn't
     * class-associated.
     */
    private static Parameter findThisParameter(Function function) {
        for (Parameter p : function.getParameters()) {
            if ("this".equals(p.getName())) {
                return p;
            }
        }
        return null;
    }
}
