name: Docker Nightly

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          cd ghidra-rpc-server
          ./build-containers.sh
          echo "pushing to ghcr.io/${{ github.repository }}"
          docker image push ghcr.io/trolldemorted/ghidra-headless-cli/ghidra-server
          docker image push ghcr.io/trolldemorted/ghidra-headless-cli/ghidra-rpc

      - name: Trigger downstream CI
        env:
          GH_TOKEN: ${{ secrets.DOWNSTREAM_PAT }}
        run: |
          gh workflow run ci.yml --repo Trolldemorted/claude-reversing
